/*
	Podagorsk classname configuration
	
	Last updated: 6:13 PM 6/21/2014
	
*/

//Do not edit this file - See config files in 'podagorsk' directory.

switch (DZAI_modName) do {
	case "epoch":
	{
		#include "epoch\dayz_epoch.sqf"
	};
	case default 
	{
		#include "podagorsk\default.sqf"
	};
};

 
